name: ppo
learning_rate: 3e-4
anneal_lr: true
gamma: 0.99
gae_lambda: 0.95
update_epochs: 4
num_minibatches: 4
clip_eps: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
norm_adv: true
clip_vloss: true
target_kl: null
